
const nycBands = [    
    "24-7 Spyz",
    "2 in a Room",
    "A Place To Bury Strangers",
    "Alice Donut",
    "AJR",
    "American Classical Orchestra",
    "American Composers Orchestra",
    "The Amygdaloids",
    "The Antlers",
    "Anthrax",
    "Axolotl" ,
    "Bad Ronald",
    "Band of Susans",
    "Barkmarket",
    "Battles",
    "Beach Fossils",
    "Beastie Boys",
    "Blondie",
    "Blood, Sweat & Tears",
    "Bloodsimple",
    "Bloody Panda",
    "The Blue Flames",
    "Blue Öyster Cult",
    "Blues Magoos",
    "Boys Choir of Harlem",
    "Brand New",
    "The Brandos",
    "Breakfast Club",
    "Brutal Truth",
    "The Cake",
    "The Candles",
    "Castevet",
    "Certain General",
    "Chairlift" ,
    "The Chiffons",
    "Circus Mort",
    "The City and Horses",
    "Class Actress",
    "The Coachmen",
    "The Cold Crush Brothers",
    "Company Flow",
    "Contre",
    "The Cro-Mags",
    "The Crystals",
    "The Davenports",
    "Deee-Lite",
    "Defunkt",
    "De La Soul",
    "DeLeon",
    "The Dictators",
    "DIIV",
    "The Diplomats",
    "Dirty Projectors",
    "DJ Logic",
    "Drowners",
    "The Drums",
    "Elephant's Memory",
    "Envy On The Coast",
    "Errortype: Eleven",
    "Even Worse",
    "Fischerspooner",
    "Four to the Bar",
    "Freelance Whales",
    "Full Blown Chaos",
    "Fun Lovin' Criminals" ,
    "Gato Loco",
    "The Ghost of a Saber Tooth Tiger",
    "Glassjaw",
    "The Golden Filter",
    "Goodbye Picasso",
    "Grizzly Bear",
    "Groove Theory",
    "Growing",
    "Grupo Latin Vibe",
    "G-Unit",
    "The Heartbreakers",
    "Richard Hell and the Voidoids",
    "Helmet",
    "Hem",
    "Hercules and Love Affair",
    "The Hold Steady",
    "Holy Ghost!",
    "The Hundred in the Hands",
    "Interpol",
    "The Indecent",
    "Ism",
    "Javelin",
    "Kid Creole and the Coconuts",
    "Kinetics & One Love",
    "Kiss",
    "LCD Soundsystem",
    "Leftöver Crack",
    "The Little Orchestra Society",
    "Life Of Agony",
    "LIPS",
    "Living Colour",
    "Lord Tariq and Peter Gunz",
    "Lotion",
    "The Lounge Lizards",
    "The Lovin' Spoonful",
    "The Mamas & the Papas",
    "Method Man & Redman",
    "Michael Hill's Blues Mob",
    "Midtown",
    "Miller Miller Miller & Sloan",
    "MisterWives",
    "MNDR",
    "Mod Fun",
    "Murphy's Law",
    "Nada Surf",
    "Naturally 7",
    "Neon Boys",
    "New York Bandura Ensemble",
    "New York Dolls",
    "New York Percussion Trio",
    "New York Philharmonic",
    "Nuclear Assault",
    "One For All",
    "Orpheus Chamber Orchestra",
    "The Pains of Being Pure at Heart",
    "Paperdoll",
    "Park Avenue Chamber Symphony",
    "Parts & Labor",
    "Pretendo",
    "The Pretty Reckless",
    "Prong",
    "PS22 chorus",
    "Public Enemy",
    "Ramones",
    "Ratatat",
    "The Ronettes",
    "The Ropes",
    "Run-DMC",
    "School of Seven Bells",
    "Scissor Sisters",
    "Seguida",
    "Sheer Terror",
    "The Shondes",
    "Shootyz Groove",
    "Shy Child",
    "Silos",
    "Simon & Garfunkel",
    "Skaters",
    "Sleigh Bells",
    "Sonic Youth",
    "Spread Eagle",
    "Startisan",
    "Steely Dan",
    "Stereobird",
    "The Steinettes",
    "The Strokes",
    "ST-X Ensemble",
    "Suffocation",
    "Swans",
    "Sylar",
   "Taking Back Sunday",
    "Talking Heads",
    "Teenage Jesus and the Jerks",
    "Television",
    "Terror Squad",
   "They Might Be Giants",
    "Tiny Masters of Today",
   "Toilet Böys",
    "Tomandandy",
    "Trachtenburg Family Slideshow Players",
    "Trilogy",
    "Type O Negative",
    "Ui",
    "The Unlovables",
    "Unsane",
    "Vampire Weekend",
   "The Velvet Underground",
    "Richard Hell and the Voidoids",
    "The Waldorf-Astoria Orchestra",
    "Weep",
    "White Zombie",
    "Wungabongas",
    "Wu-Tang Clan",
    "X27",
    "Yeah Yeah Yeahs"
 ];



 export default nycBands